rsyslog: Autospec creation for update from version 8.2212.0 to version 8.2302.0
Andre lorbach (2):
      openssl: fix undefined reference to CRYPTO_set_id_callback
      Fixed wrong type conversion in cstrLen() for debug mode as well

Flos Lonicerae (1):
      Fixed wrong type conversion in cstrLen()

LGTM Migrator (1):
      Add CodeQL workflow for GitHub code scanning

Michael Biebl (1):
      Fix typos spotted by lintian

Rainer Gerhards (17):
      bump release number for new schedule stable cycle
      core bugfix: template system may generate invalid json
      testbench: add test for invalid json template generation
      maintain ChangeLog
      CI: use newer version of zookeeper
      omfile: add action parameters "rotation.*"
      fix version number for next scheduled stable release
      substring function: enhancement and hardening
      maintain ChangeLog
      maintain ChangeLog
      maintain ChangeLog
      maintain ChangeLog
      CI: fix github CodeQL settings
      core/template: implement negative position.to
      maintain ChangeLog
      CI/QA: do compile test both with NDEBUG set/unset
      prepare for scheduled stable 8.2302.0 release

Thibaud Cartegnie (1):
      ffaup fix : memory corruption with concurrent workers

alakatos (3):
      Introduce --enable-libcap-ng configure option
      Adjust the capability set
      Remove CAP_DAC_OVERRIDE if privileges dropped

lilinjie (2):
      fix typo
      fix typo